server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: transaction_service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: transaction-service
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
      base-path: /actuator

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: transaction-service

  health:
    db:
      enabled: true

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

  otlp:
    metrics:
      export:
        enabled: true

  prometheus:
    metrics:
      export:
        enabled: true

  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.namespace: leiloeiroonline
      deployment.environment: prod

    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          protocol: http/protobuf
