server:
  port: 9082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=transaction_service
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: transaction_service
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-service
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
